### PR TITLE
Fix logic for combined matches of program and syslog_*

### LINKED ISSUE #139: Concern around 'match' logic
**Describe the bug**
The match logic in [src/processors/engine.c](https://github.com/beave/sagan/blob/master/src/processors/engine.c#L441) seems broken, since each test can cause the result of the previous test to be forgotten.

They are tested in the order:
* program
* syslog_facility
* syslog_level
* syslog_tag
* syslog_priority

But a later successful match overrides a previous failure.

**To Reproduce**
Have a rule like `program: sshd; syslog_facility: info`

This will match any message with syslog_facility info, regardless of whether the program is sshd or not.

Have a rule like `syslog_facility: mail; syslog_level: error`

This will match any message with syslog level error, regardless of whether the facility is mail or not.

**Expected behavior**
All conditions need to match.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
It's easier to think about the logic if you rename this variable in your head to "failed" or "unmatched".

While testing this I found another bug which is that the syslog match attributes are never tested anyway (#141), which means this issue is moot until that is fixed first.

### PR DESCRIPTION
**Pull request by candlerb**
Fixes #139

### CODE REVIEW

File: src/processors/engine.c [hunk 1]
```diff
@@ -440,7 +440,7 @@ int Sagan_Engine ( _Sagan_Proc_Syslog *SaganProcSyslog_LOCAL, bool dynamic_rule_
 
                     match = false;
```
Comment (beave) [inline src/processors/engine.c]: match is set here.  At the "program",  the test will always be true.  

We want these to act like an "and" statement.  For example,  if "program" and "facility" match, then fire.

Comment (candlerb) [reply src/processors/engine.c]: Yes indeed: I put it there to make it consistent with all the following tests, so that they can be moved around.  But I can remove the first one if you like.  The subsequent ones must remain.

The reason for this change is exactly to make it work as "and", which it doesn't today.

Comment (beave) [reply src/processors/engine.c]: Yep.  Just tested and you are 100% correct.   Thanks for catching that.    I was able to reproduce and the patch fixes it.. I'm going to merge.  Thanks!
